const data: Record<TProductId, TProduct> = {
    '432dfs': {
        name: 'Audífonos para videojuegos con sonido envolvente 10.2',
        id: '432dfs',
        sku: '0029',
        img: './images/c22c23_0d97e80aa2aa4072878ad49cbe04e926~mv2.webp',
        price: 984.00,
        types: 'audifono',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '456h3ui3': {
        name: 'Audífonos inalámbricos con cancelación del ruido',
        id: '456h3ui3',
        sku: '0048',
        img: './images/c22c23_0fa2a9bb97f443658acb747221ff337b~mv2.webp',
        price: 984.00,
        types: 'audifono',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '64h5jdf4': {
        name: 'Pilates laptop con pantalla táctil de 14" y 12GB de RAM',
        id: '64h5jdf4',
        sku: '0057',
        img: './images/c22c23_01a8a61a9f6c4e3a97711b8c684050e9~mv2.webp',
        price: 999.00,
        types: 'computadora',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '35l46hs': {
        name: 'Cámara digital Pantony 180 de 20,0 megapíxeles',
        id: '35l46hs',
        sku: '0034',
        img: './images/c22c23_1bef44e4aad644d88da3458c1aa9c341~mv2.webp',
        price: 999.00,
        types: 'dron y camara',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '453gse67': {
        name: 'Cámara de seguridad inalámbrica interior 1080p',
        id: '453gse67',
        sku: '0047',
        img: './images/c22c23_1fc89607a43a4df9b54dd3a1f9603f25~mv2.webp',
        price: 984.00,
        types: 'dron y camara',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'kgh5b534i': {
        name: 'Cuadricóptero Wave Mini 4 con mando a distancia',
        id: 'kgh5b534i',
        sku: '0039',
        img: './images/c22c23_2d5a87c251274b8083356fd1e61cf68d~mv2.webp',
        price: 999.00,
        types: 'dron y camara',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '3k2geq8': {
        name: 'Monitor JP 29" LED panorámico FHD',
        id: '3k2geq8',
        sku: '0022',
        img: './images/c22c23_3a1cae1c619a4bfc8c1fcfb73e5ed4e6~mv2.webp',
        price: 984.00,
        types: 'computadora',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '42kj213s': {
        name: 'JP Laptop para juegos de 15,6" de 256GB',
        id: '42kj213s',
        sku: '0041',
        img: './images/c22c23_3ab3d3acd73843deba1dece7b2254e2f~mv2.webp',
        price: 984.00,
        types: 'computadora',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '6534fsf2': {
        name: 'Cámara DSLR Pantony con objetivo 18-55mm',
        id: '6534fsf2',
        sku: '0038',
        img: './images/c22c23_3fd6a46235b34d158ce2ad1628900bb2~mv2.webp',
        price: 984.00,
        types: 'dron y camara',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '63fwf4da1': {
        name: 'Miniproyector inalámbrico JP 470',
        id: '63fwf4da1',
        sku: '0026',
        img: './images/c22c23_4fc66d5377a64a80a4c5a303bf338a5d~mv2.webp',
        price: 999.00,
        types: 'TV y cinema',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'csj34l24': {
        name: 'OVE Light Space 5G, 128GB',
        id: 'csj34l24',
        sku: '0032',
        img: './images/c22c23_5ccf45bbbdf842e7955635610510f7c3~mv2.webp',
        price: 984.00,
        types: 'celular',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'asb432df': {
        name: 'Allure 55" clase LED 4K UHD TV inteligente',
        id: 'asb432df',
        sku: '0044',
        img: './images/c22c23_6df363bec6fc43dd9d47ed2d34335417~mv2.webp',
        price: 984.00,
        types: 'TV y cinema',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'fh24h21': {
        name: 'Bocina portátil Bluetooth SDK',
        id: 'fh24h21',
        sku: '0031',
        img: './images/c22c23_7b3b59adc71d48aea694647bfb4385b8~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: false,
        BestSellers: true,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '4j224h1': {
        name: 'JP Espectro S, 5G, 16GB',
        id: '4j224h1',
        sku: '0014',
        img: './images/c22c23_7c88223cd6d647ca80670b82509dbf15~mv2.webp',
        price: 984.00,
        types: 'celular',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'ad3rwj17': {
        name: 'Proyector Wilsom Home Cinema 4K PRO-UHD 3LCD',
        id: 'ad3rwj17',
        sku: '0023',
        img: './images/c22c23_7cafe7e6503648ebbaf422161045861d~mv2.webp',
        price: 999.00,
        types: 'TV y cinema',
        offer: false,
        BestSellers: true,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'ad31j13': {
        name: 'JP - Space Tablet 10,4" Wi-Fi 32GB',
        id: 'ad31j13',
        sku: '0063',
        img: './images/c22c23_9a6d29ecf9c640b28cc79f695e9fb3c2~mv2.webp',
        price: 984.00,
        types: 'table',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '456fs244': {
        name: 'Audífonos con cable MX50',
        id: '456fs244',
        sku: '0028',
        img: './images/c22c23_9ff1bd93e19f48b19670b5f6b19e874d~mv2.webp',
        price: 999.00,
        types: 'audifono',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'as2bu55bk': {
        name: 'Shel 40" clase LED Full HD TV inteligente',
        id: 'as2bu55bk',
        sku: '0042',
        img: './images/c22c23_26dd5ed4d9c34428b4b7423e7fdddf21~mv2.webp',
        price: 984.00,
        types: 'TV y cinema',
        offer: false,
        BestSellers: true,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'csj34l2f': {
        name: 'MAX Pantony S 5G, 128GB',
        id: 'csj34l2f',
        sku: '0015',
        img: './images/c22c23_28f533b5fbdc45ed9a1b88c7e911bdd6~mv2.webp',
        price: 999.00,
        types: 'celular',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'fh24h2t': {
        name: 'Barra de sonido Bluetooth TV con conectividad HDMI',
        id: 'fh24h2t',
        sku: '0024',
        img: './images/c22c23_30fe87ca94c0479d9bc5e039301f90cf~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'v3v1w32': {
        name: 'Gafas de realidad virtual Safay GEN 2 de 256 GB con mandos táctiles',
        id: 'v3v1w32',
        sku: '004',
        img: './images/c22c23_35b786fdd0bb443e9ac09561af1569d3~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '45h42d2': {
        name: 'Audífonos inalámbricos Pantony de botón certificados',
        id: '45h42d2',
        sku: '0032',
        img: './images/c22c23_59eb04b5184848f597f1802443c62ccc~mv2.webp',
        price: 999.00,
        types: 'audifono',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'ad31j1': {
        name: 'Sheer Tablet de 10,2" con Wi-Fi , 32GB',
        id: 'ad31j1',
        sku: '0045',
        img: './images/c22c23_67a4de6683784fbbb684418e49d5d854~mv2.webp',
        price: 984.00,
        types: 'table',
        offer: false,
        BestSellers: true,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '43fs3g3': {
        name: 'Audífonos inalámbricos Space Buds True Earbud',
        id: '43fs3g3',
        sku: '0050',
        img: './images/c22c23_68efa76790cf48a7acdb518977ce72a1~mv2.webp',
        price: 999.00,
        types: 'audifono',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '43fs33g': {
        name: 'Bocina portátil Bluetooth Studio 8',
        id: '43fs33g',
        sku: '0052',
        img: './images/c22c23_68fb3f3fcf134e91a00a956483ba56f8~mv2.webp',
        price: 999.00,
        types: 'bocina',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '43fs31dd': {
        name: 'Bocina portátil con Bluetooth Turn5',
        id: '43fs31dd',
        sku: '0051',
        img: './images/c22c23_75b7c7a737a0437f8998a42d8a345a85~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '6534fsg3': {
        name: 'HKI Tech drone cuadricóptero con cámara y mando 360',
        id: '6534fsg3',
        sku: '0037',
        img: './images/c22c23_77a52a8e6f8b4879a6548e11a3df3613~mv2.webp',
        price: 984.00,
        types: 'dron y camara',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '6n24kw4': {
        name: 'Shel 50" clase LED 4K UHD Smart TV',
        id: '6n24kw4',
        sku: '001',
        img: './images/c22c23_77c2b89535374768bec1d6337dcdbddc~mv2.webp',
        price: 984.00,
        types: 'TV y cinema',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '42kj23s': {
        name: 'Corr de escritorio 24 GB de memoria + pantalla de 29" teclado y ratón',
        id: '42kj23s',
        sku: '0020',
        img: './images/c22c23_88af147a4da742eb86528c8d8e5594fd~mv2.webp',
        price: 984.00,
        types: 'computadora',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '42kj2s': {
        name: 'Sheer Pro Mini Tablet de 7,9 pulgadas',
        id: '42kj2s',
        sku: '0060',
        img: './images/c22c23_91ee238e5ee447878278fd04f4d3fafe~mv2.webp',
        price: 984.00,
        types: 'table',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '42kj2s31': {
        name: 'Pantony Super 10W 5G, 128GB',
        id: '42kj2s31',
        sku: '0013',
        img: './images/c22c23_299fed1f1efd4b4fa580ac49d00628dd~mv2.webp',
        price: 984.00,
        types: 'celular',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'v3v1wt32': {
        name: 'Space Moon Smartwatch con cargador',
        id: 'v3v1wt32',
        sku: '002',
        img: './images/c22c23_396e7b1e80764edca161180595507710~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'csj346l2f': {
        name: 'Smartphone Z Pixel Max 128GB desbloqueado',
        id: 'csj346l2f',
        sku: '0012',
        img: './images/c22c23_527e6c6f3d944fb88c80907c2f754afb~mv2.webp',
        price: 984.00,
        types: 'celular',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'c1sj346l2': {
        name: 'Cámara de seguridad Shak para exteriores',
        id: 'c1sj346l2',
        sku: '0040',
        img: './images/c22c23_717f42d8a3d648eab5245dd2025d29ac~mv2.webp',
        price: 984.00,
        types: 'dron y camara',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '42kj2sts': {
        name: 'Ove Tablet FD Plus - 10,3", 32GB',
        id: '42kj2s',
        sku: '0061',
        img: './images/c22c23_5669a61229d34b15b7ff71c4f2269a4b~mv2.webp',
        price: 984.00,
        types: 'table',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '42k23s': {
        name: 'Pilates laptop con pantalla táctil de 16" y 12GB deRAM',
        id: '42k23s',
        sku: '0021',
        img: './images/c22c23_6137a9aabb314e18bd7cbbbcb37ef185~mv2.webp',
        price: 984.00,
        types: 'computadora',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '82k2j3s': {
        name: 'Bocina Bluetooth portátil en forma de píldora plateada',
        id: '82k2j3s',
        sku: '0054',
        img: './images/c22c23_09339ee46fd441b8bdaf76b3a7081135~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '2k2j3s': {
        name: 'Audífonos Balo inalámbricos con cancelación de ruido',
        id: '2k2j3s',
        sku: '0046',
        img: './images/c22c23_65076c29d2de4910b9376408663514c2~mv2.webp',
        price: 984.00,
        types: 'audifono',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'v3v1f32': {
        name: 'Fitboot fitness con seguimiento del ritmo cardíaco',
        id: 'v3v1f32',
        sku: '003',
        img: './images/c22c23_75059a72af5e4949aecdfbda8746f4ef~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '3kl2hu3sy': {
        name: 'JP Exmax Phantom, 5G, 16GB',
        id: '3kl2hu3sy',
        sku: '0010',
        img: './images/c22c23_229835b7ed254c8c95f2b90ef1404ded~mv2.webp',
        price: 984.00,
        types: 'celular',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'adn1jn3': {
        name: 'Corr Playtime 10.3", 32GB Con Wi-Fi',
        id: 'adn1jn3',
        sku: '0058',
        img: './images/c22c23_597373dec7644ad2818277724199fb0c~mv2.webp',
        price: 984.00,
        types: 'table',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '6n34fsg3': {
        name: 'EXE Mini drone con controlador de cielo',
        id: '6n34fsg3',
        sku: '0035',
        img: './images/c22c23_607618f163cf465da48e3393dbcd871e~mv2.webp',
        price: 984.00,
        types: 'dron y camara',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'v1g2a3f4': {
        name: 'Gafas de realidad virtual Journey Glass XD',
        id: 'v1g2a3f4',
        sku: '0046',
        img: './images/c22c23_991175ea1f9140648365694757467456~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '4n2dfs': {
        name: 'Audífonos inalámbricos blancos de botón',
        id: '4n2dfs',
        sku: '0030',
        img: './images/c22c23_1752807cf4f14909a5928ba0cedb339e~mv2.webp',
        price: 984.00,
        types: 'audifono',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'jwh131d': {
        name: 'FitWatch reloj inteligente fitness',
        id: 'jwh131d',
        sku: '005',
        img: './images/c22c23_4567980aa0eb4bfba21b3706eaa8b2ca~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '2k2j5s': {
        name: 'Drums Pro audífonos inalámbricos sobre el oído',
        id: '2k2j5s',
        sku: '0049',
        img: './images/c22c23_31759778ff1248978471f8cc44c24f9d~mv2.webp',
        price: 984.00,
        types: 'audifono',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'ad2n1jn3': {
        name: 'Pilates Go 10,5" pantalla táctil, 64GB con funda',
        id: 'ad2n1jn3',
        sku: '0062',
        img: './images/c22c23_23738414163d418092290f6b9becc5f5~mv2.webp',
        price: 984.00,
        types: 'table',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'ad1n1jn3': {
        name: 'Ocean Pro 11 - Pantalla táctil de 12,3"',
        id: 'ad1n1jn3',
        sku: '0059',
        img: './images/c22c23_a055ae2dfe6f457b9c2f6f3fa6d95126~mv2.webp',
        price: 984.00,
        types: 'table',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '6n2kw4': {
        name: 'TV inteligente Nano LED 4K UHD de 65 pulgadas',
        id: '6n2kw4',
        sku: '0025',
        img: './images/c22c23_a78a3c8e4c63423ab6967f12ca17e447~mv2.webp',
        price: 984.00,
        types: 'TV y cinema',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'jw3h13n': {
        name: 'HV sistema de realidad virtual para PC',
        id: 'jw3h13n',
        sku: '006',
        img: './images/c22c23_a79ca5eba4af45bc99bf27f0d9eb637d~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '12k2j3s': {
        name: 'Barra de sonido Bluetooth TV con conectividad HDMI',
        id: '12k2j3s',
        sku: '0055',
        img: './images/c22c23_bb3cb6edf9ff4594817c7a2aaedd2a15~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    'c142sd4': {
        name: 'Minicámara digital impermeable',
        id: 'c142sd4',
        sku: '0036',
        img: './images/c22c23_c25f748ee2264db6a3767d99717a2b84~mv2.webp',
        price: 984.00,
        types: 'dron y camara',
        offer: true,
        BestSellers: true,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '6n2k13s': {
        name: 'TV inteligente de alta definición de 42 pulgadas',
        id: '6n2k13s',
        sku: '0025',
        img: './images/c22c23_a78a3c8e4c63423ab6967f12ca17e447~mv2.webp',
        price: 984.00,
        types: 'TV y cinema',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '6n1k13s': {
        name: 'Laptop Pilates con pantalla táctil de 16" y 24GB de RAM',
        id: '6n1k13s',
        sku: '0043',
        img: './images/c22c23_c4329067853e4f94a57afc2a226bd5cf~mv2.webp',
        price: 984.00,
        types: 'computadora',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '612k13s': {
        name: 'Pantony 6P reloj de actividad',
        id: '612k13s',
        sku: '007',
        img: './images/c22c23_d898eb06de73454788ddf633d055e85b~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '3nk2j3s': {
        name: 'Mini altavoz portátil redondo con Bluetooth',
        id: '3nk2j3s',
        sku: '0053',
        img: './images/c22c23_d4488c12f2bc40dfbd1bbd82956eb97a~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '3nk2a3s': {
        name: 'Mini altavoz portátil Bluetooth SXD',
        id: '3nk2a3s',
        sku: '0033',
        img: './images/c22c23_d07318f25e874d25b1151a36333e8fcb~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '3n32a3s': {
        name: 'Bocina portátil Bluetooth Turn5 con asa',
        id: '3n32a3s',
        sku: '0056',
        img: './images/c22c23_dbf65eb585cf415ba135313576716352~mv2.webp',
        price: 984.00,
        types: 'bocina',
        offer: true,
        BestSellers:false,
        priceOffer: 999.00,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '61k13s': {
        name: 'FitWatch XDH reloj inteligente de fitness',
        id: '61k13s',
        sku: '008',
        img: './images/c22c23_ee8bc28108d44d34b0ed1b312845667f~mv2.webp',
        price: 984.00,
        types: 'technology',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
    '3kl2n3sy': {
        name: 'Pantony X21 5G, 128GB con lápiz Z',
        id: '3kl2n3sy',
        sku: '009',
        img: './images/c22c23_f37a0a50f81146d7bbaf5edb5803cd9f~mv2.webp',
        price: 984.00,
        types: 'celular',
        offer: false,
        BestSellers:false,
        attributes: {
            info: 'Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios.',
            policy: 'Política de devolución y reembolso. Lugar ideal para explicar a tus clientes qué hacer si no están satisfechos con su compra. Tener una política de reembolso o cambio clara es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            shipment: 'Política de envío. Lugar ideal para agregar más información sobre tus métodos de envío, empaquetado y costos. Brindar información clara sobre tu política de envío es una gran manera de generar confianza y garantizar que tus clientes compren con seguridad.',
            description: 'Descripción del producto. Lugar ideal para "vender" tu producto y captar la atención del comprador. Describe tu producto de forma clara y precisa. Usa palabras únicas. Escribe tu propia descripción en vez de usar la del fabricante.',
        },
    },
}

export default data