import { Footer } from "../../components/footer/Footer";
import Nav from "../../components/nav/Nav";
import "./globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body>
        <div className="ContMax">
          <Nav/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
